# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true
paginate_path:       page/:num

# Setup
title:               arcestia
tagline:             Social Media Addict, Writer, open source developer
url:                 http://me.arcestia.id
paginate:            10
baseurl:             ""
google_verify:

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Laurensius Jeffrey Chandra
  url:               http://me.arcestia.id
  email:             vrusolik@gmail.com

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/arcestiaishere/arcestiaishere.github.io

# This is the list of pages to include in the header of the website.
pages_list:
  Categories: /categories
  Facebook: https://facebook.com/Arcestia
  Twitter: https://twitter.com/LizSnowy

# Disqus
disqus:
  shortname: 'arcestia'
  count: 5
  api_key: "gy7BKcBNNp58VBQMCbi7Fdm0o3JSSbcvu0m4LBUWmRrhkrJaQrVxNQaNj2sC4dg1"

# Plugin
gems:
  - jekyll-sitemap
